INSERT INTO product (brand, code, name, price, type) VALUES
                    ('Green Harvest', 111, 'Organic Olive Oil', 12.99, 'Food'),
                    ('Health Haven', 222, 'Quinoa Salad Mix', 8.49, 'Food'),
                    ('Gourmet Delights', 333, 'Artisanal Cheese Selection', 19.99, 'Food'),
                    ('Seafood Sensations', 444, 'Fresh Salmon Fillet', 16.99, 'Food'),
                    ('Tropical Treats', 555, 'Exotic Fruit Medley', 14.99, 'Food'),
                    ('Fashion Forward', 666, 'Stylish Sunglasses', 29.99, 'Clothing'),
                    ('Winter Wardrobe', 777, 'Cozy Knit Sweater', 39.99, 'Clothing'),
                    ('Urban Chic', 888, 'Leather Crossbody Bag', 49.99, 'Clothing'),
                    ('Active Lifestyle', 999, 'Running Shoes', 54.99, 'Clothing'),
                    ('Elegant Attire', 101, 'Formal Blazer', 89.99, 'Clothing'),
                    ('Sonic Bliss', 202, 'Noise-Canceling Headphones', 129.99, 'Electronics'),
                    ('Tech Vision', 303, '4K Smart TV', 599.99, 'Electronics'),
                    ('Photo Pro', 404, 'DSLR Camera Kit', 799.99, 'Electronics'),
                    ('Audio Hub', 505, 'Portable Bluetooth Speaker', 39.99, 'Electronics'),
                    ('Power Play', 606, 'Gaming Laptop', 1299.99, 'Electronics');