version: '3.8'
services:
  ## MYSQL - Database for Users
  db_users:
    container_name: db_users
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_users
      MYSQL_USER: dixonpa
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_mysql/01_table_users.sql:/docker-entrypoint-initdb.d/01_table_users.sql
    ports:
      - "3311:3306"
    expose:
      - 3311